### GET Hello
GET http://localhost:3000/test/hello

### GET Places 1
GET http://localhost:3000/places?text=av governador valadares, betim, 1000

### GET Places 2
GET http://localhost:3000/places?text=av amazonas, belo horizonte, 1000

### GET Directions
@originId = EkBBdi4gR292LiBWYWxhZGFyZXMsIDEwMDAgLSBDZW50cm8sIEJldGltIC0gTUcsIDM2NDEwLTAyNiwgQnJhc2lsIjESLwoUChIJqWNAFJLDpgARpsy5kCM5OC8Q6AcqFAoSCXkSTsuRw6YAETPuVaoFp4Tx
@destinationId = ChIJPUqddeKZpgARusD9CDpIBDQ
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}

### CREATE Route
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

### GET routes
GET http://localhost:3000/routes

### GET route
GET http://localhost:3000/routes/675c7b4ad917819686d1e309

### Start route
POST http://localhost:3000/routes/675c7b4ad917819686d1e309/start
